# Embedding
The `torch.nn.Embedding` layer maps indices to dense vectors. It’s useful when you want to get a vector representation for each discrete input (e.g., a word or token).

**Explanation**:
- `num_embeddings=3`: The number of unique tokens in the vocabulary (3 in this case).
- `embedding_dim=5`: The size of the embedding vector for each token.
The output will be a dense matrix of shape [3, 5] (3 tokens, each represented by a 5-dimensional vector).

In [1]:
import torch
import torch.nn as nn

# Define the embedding layer
embedding = nn.Embedding(num_embeddings=3, embedding_dim=5)

# Input indices for the sentence "I love AI"
input_indices = torch.tensor([0, 1, 2])  # [I, love, AI]

# Get the embeddings
output = embedding(input_indices)
print("Embedding Output:")
print(output)


Embedding Output:
tensor([[-0.3792,  0.4097,  0.5401, -0.8731,  1.1601],
        [ 0.3585,  0.7492, -0.7993, -0.2771,  0.1574],
        [ 0.5417, -0.5474, -0.3932,  0.0042,  0.6709]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
import torch
import torch.nn as nn

# Define the embedding layer
embedding = nn.Embedding(num_embeddings=3, embedding_dim=5)

# Input indices for the sentence "I love AI"
input_indices = torch.tensor([0, 1, 2])  # [I, love, AI]

# Get the embeddings
output = embedding(input_indices)
print("Embedding Output:")
print(output)


Embedding Output:
tensor([[-0.3792,  0.4097,  0.5401, -0.8731,  1.1601],
        [ 0.3585,  0.7492, -0.7993, -0.2771,  0.1574],
        [ 0.5417, -0.5474, -0.3932,  0.0042,  0.6709]],
       grad_fn=<EmbeddingBackward0>)


# Embedding Bag
`torch.nn.EmbeddingBag` computes embeddings for a batch of sequences but applies pooling (e.g., summing, averaging) to combine embeddings for sequences. It’s efficient for tasks where you only need aggregated representations, like sentence-level embeddings.

In [2]:
# Define the embedding bag layer
embedding_bag = nn.EmbeddingBag(num_embeddings=5, embedding_dim=5, mode='mean')

# Input indices for the sentences
input_indices = torch.tensor([0, 1, 2, 2, 3, 4])  # [I, love, AI, AI, is, great]

# Offsets to define where each sentence starts
offsets = torch.tensor([0, 3])  # Sentence 1 starts at index 0, Sentence 2 at index 3

# Get the aggregated embeddings
output = embedding_bag(input_indices, offsets)
print("EmbeddingBag Output:")
print(output)


EmbeddingBag Output:
tensor([[ 0.9563,  0.8776, -0.3627,  0.7169,  0.7994],
        [ 0.1821, -0.5768,  0.4983, -0.3879, -0.7234]],
       grad_fn=<EmbeddingBagBackward0>)


- **Embedding**: The output for the individual words "I", "like", and "cats" will be three separate vectors.
- **Embedding Bag**: The output will be a single vector that represents the average of the embeddings for "I", "like", and "cats".